Added use case examples for File Identifiers
Vinzent03/obsidian-advanced-uri pull request #95
Opened 2022-12-04 07:00 UTC by Gr-Nobel

- added 3 examples with real life use cases with sample images. Limitations:
- I couldn't use styling while adding those examples
- I don't know the use of uid .

2022-12-07 20:20 UTC, Vinzent03 requested changes
Thanks for improving the documentation. Some changes needed, though.

2022-12-07 20:20 UTC, Vinzent03 commented on docs/docs/concepts/file_identifiers.md
> +obsidian://advanced-uri?&filepath=Inbox
Please surround the uri with backticks(`) to style them like code

2022-12-07 20:20 UTC, Vinzent03 commented on docs/docs/concepts/file_identifiers.md
> +this will open a note "Inbox" in your obsidian vault if there is no inbox note
Start the sentence with a capital letter. What do you mean with this?
> if there is no inbox note

2022-12-07 20:20 UTC, Vinzent03 commented on docs/docs/concepts/file_identifiers.md
> +Suppose you have note called inbox which has a alias "Brain Dumps" . Now comes the use case for filename.
```suggestion
Suppose you have a note called inbox which has an alias "Brain Dumps". Now comes the use case for filename.
```

2022-12-08 11:30 UTC, Vinzent03 commented on docs/docs/concepts/file_identifiers.md
> +obsidian://advanced-uri?&filepath=Inbox
@Gr-Nobel I din't mean brackets,but backticks: `

2022-12-13 10:18 UTC, Vinzent03 commented on docs/docs/concepts/file_identifiers.md
> +Suppose you have a note called inbox which has an alias "Brain Dumps". Now comes the use case for filename.
```suggestion
Suppose you have a note called Inbox which has an alias "Brain Dumps". Now comes the use case for the `filename` parameter.
```

2022-12-13 10:19 UTC, Vinzent03 commented on docs/docs/concepts/file_identifiers.md
> +this will open your daily note and place the cursor under Inbox heading if there is one.
```suggestion
This will open your daily note and place the cursor under Inbox heading if there is one.
```

2022-12-17 06:23 UTC, Gr-Nobel commented
Ok

2022-12-17 22:42 UTC, Vinzent03 approved these changes

2022-12-17 22:42 UTC, Vinzent03 commented
Thanks for your contribution!

2022-12-17 22:42 UTC, merged